[tool.black]
line-length = 80
skip-string-normalization = false
skip-magic-trailing-comma = true

[tool.pydoctor]
add-package = ["wropen"]
docformat = "restructuredtext"
verbose = 1
warnings-as-errors = false
html-output = "./doc"
theme = "readthedocs"
