name: wropen
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyton-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install pip --upgrade
          python --version
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint
        run: make lint
      - name: docs
        run: make docs
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: doc
          path: doc
        if: ${{ always() }}
